name: ketchapp_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI components
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  flutter_ruler_picker: ^1.0.6
  introduction_screen: ^3.1.17
  dynamic_color: ^1.7.0

  # Navigation
  go_router: ^15.1.2

  # Network
  http: ^1.3.0

  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.2.1

  # State management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  # UI components
  confetti: ^0.8.0 # Added confetti package
  shimmer: ^3.0.0

  # Utils
  uuid: ^4.5.1
  intl: ^0.20.2

  # Google APIs per Google Calendar
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  url_launcher: ^6.3.0 # Utile per aprire link, potrebbe servire per la gestione dei permessi
  image_picker: ^1.0.7 # Per la selezione delle immagini
  image_cropper: ^9.1.0 # Per il ritaglio delle immagini
  firebase_storage: ^12.4.6 # Per il caricamento delle immagini su Firebase Storage 
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
